_target_: tava.datasets.h36m_zju_loader.SubjectLoader

subject_id: S9
root_fp: "./data/h36m_zju/"
split: ???  # to be defined in the code
resize_factor: 1.0
color_bkgd_aug: "random"
num_rays: 1024
cache_n_repeat: 5
near: null
far: null
legacy: true

# parameters used by models
pose_latent_dim: 78
n_transforms: 19
world_dist: 0.3
cano_dist: 0.3